version: "3.8"
services:
  # nginx:
  #   build: 
  #     context: ./docker/nginx
  #     dockerfile: Dockerfile
  #     args:
  #       - DEFAULT_PORT=80
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #     - ./ssl:/etc/nginx/ssl
  #   container_name: nginx
  #   depends_on:
  #     - backend
  #     - proxy

  # proxy:
  #   build: 
  #     context: ./docker/proxy
  #     dockerfile: Dockerfile
  #     args:
  #       - DEFAULT_PORT=80
  #   ports:
  #     - "80:80"
  #   volumes: 
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend

  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./backend/.env
    container_name: mongodb
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DEFAULT_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - logs:/app/logs
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    container_name: backend
    stdin_open: true
    tty: true
    
  # frontend:
  #   build: 
  #     context: ./tsx-front
  #     dockerfile: Dockerfile
  #     args:
  #       - DEFAULT_PORT=3000
  #   ports:
  #     - "3000:3000"
  #   volumes: 
  #     - ./tsx-front/src:/app/src
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend

volumes:
  data:
  logs: